# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodu', models.CharField(max_length=10)),
                ('adi', models.CharField(max_length=50)),
                ('tanimi', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numarasi', models.IntegerField()),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=50)),
                ('aldigi_dersler', models.ManyToManyField(to='yonetim.Ders')),
            ],
        ),
        migrations.CreateModel(
            name='OgretimElemanlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=10)),
                ('e_posta_adresi', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='ders',
            name='ogretim_elemani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonetim.OgretimElemanlari'),
        ),
    ]
